# Generated by Django 2.1.3 on 2018-11-14 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdakun', models.IntegerField(null=True)),
                ('nmakun', models.CharField(max_length=100)),
                ('kdjenbel', models.IntegerField(null=True)),
                ('tahun', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Bulan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdbulan', models.IntegerField(null=True)),
                ('nmbulan', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kddept', models.IntegerField(null=True)),
                ('nmdept', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Fungsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdfungsi', models.IntegerField(null=True)),
                ('nmfungsi', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Giat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdsfungsi', models.IntegerField(null=True)),
                ('kdgiat', models.IntegerField(null=True)),
                ('nmgiat', models.CharField(max_length=70)),
                ('versi', models.CharField(max_length=25)),
                ('tahun', models.DateField()),
                ('kdfungsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Fungsi')),
            ],
        ),
        migrations.CreateModel(
            name='Kotam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdkotama', models.IntegerField(null=True)),
                ('nmkotama', models.CharField(max_length=255)),
                ('kdkukotama', models.CharField(max_length=255)),
                ('kddept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Dept')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdsfungsi', models.IntegerField(null=True)),
                ('kdprogram', models.IntegerField(null=True)),
                ('nmprogram', models.CharField(max_length=45)),
                ('tahun', models.DateField()),
                ('versi', models.CharField(max_length=20)),
                ('kdfungsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Fungsi')),
            ],
        ),
        migrations.CreateModel(
            name='Satkr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdsatkr', models.IntegerField(null=True)),
                ('nmsatkr', models.CharField(max_length=80)),
                ('kddept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Dept')),
                ('kdkotama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Kotam')),
            ],
        ),
        migrations.CreateModel(
            name='Satkun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdoutput', models.CharField(max_length=3)),
                ('kdsakun', models.IntegerField(null=True)),
                ('nmsakun', models.CharField(max_length=255)),
                ('kddipa', models.IntegerField(null=True)),
                ('kdakun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Akun')),
                ('kdgiat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Giat')),
            ],
        ),
        migrations.CreateModel(
            name='Subsatkr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdsubsatkr', models.IntegerField(null=True)),
                ('nmsubsatkr', models.CharField(max_length=100)),
                ('kddept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Dept')),
                ('kdkotama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Kotam')),
                ('kdsatkr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Satkr')),
            ],
        ),
        migrations.CreateModel(
            name='Tingkat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdtingkat', models.IntegerField(null=True)),
                ('pengguna', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdunit', models.IntegerField(null=True)),
                ('nmunit', models.CharField(max_length=60)),
                ('kddept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Dept')),
            ],
        ),
        migrations.CreateModel(
            name='Wasgiat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdwasgiat', models.IntegerField(null=True)),
                ('nmwasgiat', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='tingkat',
            name='kdwasgiat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Wasgiat'),
        ),
        migrations.AddField(
            model_name='subsatkr',
            name='kdunit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Unit'),
        ),
        migrations.AddField(
            model_name='satkr',
            name='kdkusatker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Satkun'),
        ),
        migrations.AddField(
            model_name='satkr',
            name='kdunit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Unit'),
        ),
        migrations.AddField(
            model_name='kotam',
            name='kdunit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Unit'),
        ),
        migrations.AddField(
            model_name='giat',
            name='kdprogram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Program'),
        ),
    ]
