# Generated by Django 2.1.3 on 2018-11-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kegiatan',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
